### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by mitlernen** [ocknamo/n8n-nodes-nostrobots#5]
![image](https://github.com/ocknamo/n8n-nodes-nostrobots/assets/107308659/3db429c4-19c1-4c8d-a68f-66b9b0a7d95e)

All I can find in the logs is: 

```npm command failed
InternalServerError: Error loading package "n8n-nodes-nostrobots" :Package could not be installed - check logs for details
```

I'm using version 1.3.1. Maybe you need to make some changes to be comparable with version 1.x.x.

**Comment by ocknamo** [comment]
@mitlernen  Thank you your reporting.

But I could not reproduce the problem in my local environment.

I can install on n8n@1.3.1 in my local.

So please give me additional information.

- platform: OS, browser, etc
- n8n execution environment. Nodejs or docker or ...?

**Comment by ocknamo** [comment]
<img width="1501" alt="n8n_-_Workflow_Automation" src="https://github.com/ocknamo/n8n-nodes-nostrobots/assets/28864753/ce739021-06f6-4a21-92a1-42ce8761ee38">

**Comment by mitlernen** [comment]
I'm running the docker image on a raspberry pi 4 with 8 GB of ram. Its arm64. If you need any more information dont hesitate.

**Comment by ikuradon** [comment]
I think this problem is probably caused by the fact that utf-8-validate is not pre-built for aarch64/arm64 and n8nio/n8n images do not include Python.

log on arm64 instance
```
~ $ npm i n8n-nodes-nostrobots
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'n8n-nodes-nostrobots@0.2.1',
npm WARN EBADENGINE   required: { node: '<=18.15.0', yarn: '~1.22.5' },
npm WARN EBADENGINE   current: { node: 'v18.16.1', npm: '9.5.1' }
npm WARN EBADENGINE }
npm ERR! code 1
npm ERR! path /home/node/node_modules/utf-8-validate
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python You need to install the latest version of Python.
npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
npm ERR! gyp ERR! find Python you can try one of the following options:
npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python For more information consult the documentation at:
npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
npm ERR! gyp ERR! stack     at exithandler (node:child_process:427:5)
npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:439:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:476:16)
npm ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR! gyp ERR! System Linux 5.15.0-1040-oracle
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/node/node_modules/utf-8-validate
npm ERR! gyp ERR! node -v v18.16.1
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2023-08-23T11_20_28_583Z-debug-0.log
```

**Comment by ikuradon** [comment]
If you want to install it anyway, you can use the following method:
1. Install package with node:18 image
```
# docker run --rm -it -v ~/.n8n:/home/node/.n8n -w /home/node/.n8n/nodes --user 1000 --entrypoint /bin/bash node:18
node@8e76ea2c682f:~/.n8n/nodes$ npm install --save n8n-nodes-nostrobots
```
(Change ~/.n8n to your configured mount directory on n8n container)

2. Install again with WebUI

**Comment by mitlernen** [comment]
sadly it doesnt work I got the same error like you @ikuradon but without the python error. 

```
node@003e07f7b492:~/.n8n/nodes$ npm install --save n8n-nodes-nostrobots
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'n8n-nodes-nostrobots@0.2.1',
npm WARN EBADENGINE   required: { node: '<=18.15.0', yarn: '~1.22.5' },
npm WARN EBADENGINE   current: { node: 'v18.17.1', npm: '9.6.7' }
npm WARN EBADENGINE }

up to date, audited 29 packages in 2s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice 
npm notice New minor version of npm available! 9.6.7 -> 9.8.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.8.1
npm notice Run npm install -g npm@9.8.1 to update!
npm notice 
```

**Comment by ikuradon** [comment]
@mitlernen After installing with command, did you install it again from the n8n WebUI? It should probably install without error.

**Comment by mitlernen** [comment]
yes i tried to install it with the n8n webui. Here is a screenshot: 

![image](https://github.com/ocknamo/n8n-nodes-nostrobots/assets/107308659/a20f6598-9dea-4b8f-b05f-cb4ceed58020)

**Comment by ocknamo** [comment]
@mitlernen 
I do not know for sure because we have not been able to reproduce it. Please consider it only as a reference.

Your `npm install --save n8n-nodes-nostrobots` execution results show a warning, but the installation seems to be working.

It is puzzling that you are able to install on the command line but not via the WebUI.

Please make sure that the command line installation is running in the same Docker container as the WebUI.

**Comment by ocknamo** [comment]
FYI. If we can replace nostr-tools in the future, the problem may be solved, but it will probably take a long time.
